name: Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:

    name: Test ${{ matrix.name_suffix }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1", "8.2", "8.3", "8.4" ]
        dependencies: [ "locked", "highest", "lowest" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: libxml, simplexml
          tools: composer:${{ matrix.composer_version }}

      - name: Install Composer dependencies
        run: composer update --no-interaction --no-progress --no-suggest --with=symfony/config:${{ matrix.symfony_constraint }}

      - name: Run PHPUnit tests
        run: composer test

  coverage:
    runs-on: ubuntu-latest
    name: Code Coverage Report
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: libxml, simplexml, xdebug
          tools: composer:'2.8'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPUnit tests with coverage
        run: composer test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: .build/coverage/clover.xml
          retention-days: 5

  coverage-report:
    name: Report test coverage
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report

      - name: Coveralls report
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ steps.download.outputs.download-path }}/clover.xml
